import type { NextPage } from 'next'
import Head from 'next/head'
import { useQuery } from '@apollo/client';
import { USER_QUERY } from '../gql/queries';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {

  const { loading, error, data } = useQuery(USER_QUERY);

  if (loading) return <p>Loading...</p>;
  if (error) return <p>Error :(</p>;

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <p>{JSON.stringify(data, ' ', 2)}</p>
      </main>
    </div>
  )
}

export default Home
